// <auto-generated />
using System;
using HowAreYou.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HowAreYou.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220121062255_worldstats")]
    partial class worldstats
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("BlazorLinks.Data.SentimentAI", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sentiment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("SentimentScore")
                        .HasColumnType("REAL");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SentimentAIs");
                });

            modelBuilder.Entity("BlazorLinks.Data.WorldSentimentData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<float>("SentimentScore")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("WorldSentimentDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
